language: javascript
sudo: false

matrix:
  include:
    #==============================
    #
    #     osx 
    #
    #==============================

    - os: osx
      osx_image: xcode7.3

    - os: osx
      osx_image: xcode8

    - os: osx
      osx_image: xcode8.3

    - os: osx
      osx_image: xcode9

    - os: osx
      osx_image: xcode9.1

    - os: osx
      osx_image: xcode9.2

    - os: osx
      osx_image: xcode9.3

    - os: osx
      osx_image: xcode9.4

    - os: osx
      osx_image: xcode10

    #==============================
    #
    #     linux 
    #
    #==============================
    
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - npm

before_install:
  - eval

install:
  - npm -g install acorn

script:
  -  for f in Src/*js ; do acorn --silent $f ; done