name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Package
        run: npm install --prefix=$HOME/.local --global acorn

      - name: Acorn
        run:  for f in src/*js ; do acorn --silent $f ; done